### ISSUE TITLE
Crash and subsequent error when deleting bag from vault list

### ISSUE THREAD

**Issue by buonviri** [TomVanRoy/Discworld-MUD-Plugins#1]
After hitting the 'Delete' link to remove my black velvet bag from the list, viewing the contents caused this:

`Run-time error
Plugin: UmivenVault (called from world: Discworld)
Function/Sub: ContainerTriggerContainerContents called by trigger
Reason: processing trigger "" when matching line: "It is over half full with: 10 Ankh-Morpork royals, some Ankh-Morpork ten-dollars, some Ankh-Morpork dollars, one Ankh-Morpork half-dollar, 2 Ankh-Morpork ten-pence and 6 Ankh-Morpork pence, two rashers of extra-crispy bacon, two handfuls of ground oregano, a pair of silver-framed spectacles, seven handfuls of ground cinnamon, seven handfuls of cumin, seven handfuls of black pepper, seven handfuls of methi, seven handfuls of ground basil, seven handfuls of ground thyme, seven handfuls of ground parsley, some fine grey ash, seven handfuls of ground fennel, seven handfuls of ground ginger, seven handfuls of ground cardamom, seven handfuls of ground coriander, seven handfuls of ground sage, sixteen strips of black cloth, seven handfuls of cloves, seven handfuls of ground turmeric, eight sheets of cheap writing paper, a small leather shield, seven handfuls of sumac, some curry powder, six handfuls of saffron, seven handfuls of caraway and many nutmegs."
[string "Plugin: UmivenVault"]:1257: table index is nil
stack traceback:
        [string "Plugin: UmivenVault"]:1257: in function 'VaultConvertContentStringToArray'
        [string "Plugin: UmivenVault"]:1742: in function 'ContainerContainerContents'
        [string "Plugin: UmivenVault"]:1720: in function <[string "Plugin: UmivenVault"]:1716>`

And subsequent attempts result in this:

`Trigger function "ContainerTriggerContainerContents" not found or had a previous error.`

**Comment by TomVanRoy** [comment]
The plugin could not handle items that were quantified with numerals, only number words (it couldn't handle 6, only 'six'). This had now been fixed to support numerals as well.
